name: banking
description: An open banking client for interacting with PSD2-compliant banking services.
version: 0.0.1
author: Arne Molland <arneolaim@gmail.com>
homepage: https://github.com/arnemolland/banking


environment:
  sdk: ">=2.1.0 <3.0.0" 
  
dependencies:
  http: ^0.12.0

dev_dependencies:
  test: ^1.5.3
  dotenv: ^1.0.0